# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo_act', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Codigo De La Actividad')),
                ('nombr_acti', models.CharField(max_length=150, verbose_name='Nombre De La Actividad')),
                ('descripcio', models.TextField(max_length=500, verbose_name='Descripci\xf3n')),
                ('fecha_inic', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fina', models.DateField(verbose_name='Fecha Final')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('cedula_alumno', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Cedula')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(max_length=50, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('sexo_alumno', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=2, max_length=10, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha De Nacimiento')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='Lugar De Nacimiento')),
                ('nacionalidad', models.CharField(choices=[('V', 'V'), ('E', 'E')], default=2, max_length=5, verbose_name='Nacionalidad')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entid_feder', models.CharField(choices=[('Distrito Capital', 'Distrito Capital'), ('Miranda', 'Miranda'), ('Aragua', 'Aragua'), ('Monagas', 'Monagas'), ('Falcon', 'Falcon'), ('Carabobo', 'Carabobo'), ('Nueva Esparta', 'Nueva Esparta'), ('Anzoategui', 'Anzoategui'), ('Vargas', 'Vargas'), ('Zulia', 'Zulia'), ('Bolivar', 'Bolivar'), ('Lara', 'Lara'), ('Merida', 'Merida'), ('Tachira', 'Tachira'), ('Guarico', 'Guarico'), ('Cojedes', 'Cojedes'), ('Trujillo', 'Trujillo'), ('Barinas', 'Barinas'), ('Sucre', 'Sucre'), ('Yaracuy', 'Yaracuy'), ('Portuguesa', 'Portuguesa'), ('Delta Amacuro', 'Delta Amacuro'), ('Apure', 'Apure'), ('Amazonas', 'Amazonas')], default=0, max_length=20, verbose_name='Entidad Federal')),
                ('ciudad', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('barri_urban', models.CharField(max_length=250, verbose_name='Barrio/Urbanizacion')),
                ('calle_avend', models.CharField(max_length=150, verbose_name='Calle/Avenida')),
                ('apt_casa', models.CharField(max_length=100, verbose_name='APTO/Casa N\xb0')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Educa_Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_uno', models.BooleanField(default=False, verbose_name='Nivel I')),
                ('nivel_dos', models.BooleanField(default=False, verbose_name='Nivel II')),
                ('nivel_tres', models.BooleanField(default=False, verbose_name='Nivel III')),
                ('nivel_cuar', models.BooleanField(default=False, verbose_name='Nivel IV')),
                ('primer_grado', models.BooleanField(default=False, verbose_name='Primer Grado')),
                ('segundo_grado', models.BooleanField(default=False, verbose_name='Primer Grado')),
                ('tercer_grado', models.BooleanField(default=False, verbose_name='Segundo Grado')),
                ('cuarto_grado', models.BooleanField(default=False, verbose_name='Cuarto Grado')),
                ('quinto_grado', models.BooleanField(default=False, verbose_name='Quinto Grado')),
                ('sexto_grado', models.BooleanField(default=False, verbose_name='Sexto Grado')),
                ('educ_med_uno', models.BooleanField(default=False, verbose_name='Media I')),
                ('educ_med_dos', models.BooleanField(default=False, verbose_name='Media II')),
                ('primer', models.BooleanField(default=False, verbose_name='Primer A\xf1o')),
                ('segund', models.BooleanField(default=False, verbose_name='Segundo A\xf1o')),
                ('tercer', models.BooleanField(default=False, verbose_name='Tercer A\xf1o')),
                ('cuarto', models.BooleanField(default=False, verbose_name='Cuarto A\xf1o')),
                ('quinto', models.BooleanField(default=False, verbose_name='Quinto A\xf1o')),
                ('curso', models.CharField(max_length=100)),
                ('cedula_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Educa_Musi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progama_orque', models.CharField(max_length=100, verbose_name='Programas Orquestales Y/O Corales En Los Que Participa')),
                ('instru_princi', models.CharField(max_length=100, verbose_name='Instrumento Principal')),
                ('instru_secund', models.CharField(max_length=100, verbose_name='Instrumento Secundario')),
                ('prof_clas_ind', models.CharField(max_length=100, verbose_name='Profesor De Clase Individial')),
                ('academ_catedr', models.BooleanField(default=False, verbose_name='El Alumno Recibe Clases En Una Academia O Catedra Nacional?')),
                ('nombr_academi', models.CharField(max_length=100, verbose_name='Escriba El Nombre De La Catedra Nacional En La Cual Cursa Estudios')),
                ('clas_acad_cate', models.CharField(max_length=100, verbose_name='Ha Sido Selecionado(a) Para Pertenecer A Una Orquesta/Coro Nacional?')),
                ('nom_aca_cate', models.CharField(max_length=100, verbose_name='Ha Sido Selecionado(a) Para Pertenecer A Una Orquesta/Coro Regional?')),
                ('inst_espc_mus', models.CharField(max_length=100, verbose_name='Cursa Estudios En Una Institucion Especializada En Musica?')),
                ('bec_est_esp', models.BooleanField(default=False, verbose_name='Recibe Alguna Beca O Ayuda Para Cursar Estudios Especializados En Musica?')),
                ('estu_cur', models.CharField(max_length=100, verbose_name='Que Estudios Cursa?')),
                ('inst_empr_bec', models.CharField(max_length=100, verbose_name='Que Institucion O Empresa Otorga La Beca')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empre', models.CharField(max_length=150, verbose_name='Nombre De La Empresa')),
                ('nombre_jefe', models.CharField(max_length=100, verbose_name='Jefe De La Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('cedula_familia', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_familia', models.CharField(max_length=50)),
                ('apelli_familia', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('telef_cel', models.IntegerField(verbose_name='Telefono Celular')),
                ('telef_res', models.IntegerField(verbose_name='Telefono De Residencia')),
                ('vive', models.BooleanField(default=False, verbose_name='Vive Con Familia?')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombr_instr', models.CharField(choices=[('Programa Alma Llanera', 'Programa Alma Llanera'), ('Arpa Clasica', 'Arpa Clasica'), ('Orquesta Infantil', 'Orquesta Infantil'), ('Oboe', 'Oboe'), ('Cuatro', 'Cuatro'), ('Percusion', 'Percusion'), ('Violincello', 'Violincello'), ('Trombon', 'Trombon'), ('Coro/Lenguaje Musical', 'Coro/Lenguaje Musical'), ('Flauta/Lenguaje Musical', 'Flauta/Lenguaje Musical'), ('Corno', 'Corno'), ('Guitarra', 'Guitarra'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Viola/Lenguaje Musical', 'Viola/Lenguaje Musical'), ('Flauta', 'Flauta'), ('Clarinete', 'Clarinete'), ('Tuba', 'Tuba'), ('Trompeta/Lenguaje Musical', 'Trompeta/Lenguaje Musical'), ('Contrabajo', 'Contrabajo'), ('Pianista', 'Pianista')], max_length=50, unique=True, verbose_name='Nombre Del Instrumento')),
                ('stock_min', models.IntegerField(default=0, verbose_name='Stock Minimo')),
                ('stock_max', models.IntegerField(default=0, verbose_name='Stock Maximo')),
                ('uso', models.IntegerField(default=0, verbose_name='En Uso')),
            ],
        ),
        migrations.CreateModel(
            name='Percep_nino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sien_bie', models.BooleanField(default=False, verbose_name='Me Siento Bien')),
                ('m_sien_seg', models.BooleanField(default=False, verbose_name='Me Siento Seguro')),
                ('sien_mejo', models.BooleanField(default=False, verbose_name='Siento Que He Mejorado Como Ser Humano')),
                ('mas_apre_com', models.BooleanField(default=False, verbose_name='Soy Mas Apreciado En La Comunidad')),
                ('m_sien_cap', models.BooleanField(default=False, verbose_name='Me Siento Cansado')),
                ('m_sien_mot', models.BooleanField(default=False, verbose_name='Me Siento Desmotivado')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Percep_Repre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_fam_reco_com', models.BooleanField(default=False, verbose_name='Como Grupo Familiar Somos Reconocidos En La Comunidad (Nos Respetan Mas)')),
                ('asis_nin_act_mus', models.BooleanField(default=False, verbose_name='La Asistencia De Mis Ni\xf1os Al La Actividad Musical, Mejoro Las Relaciones Familiares')),
                ('prac_mus_ent_eco', models.BooleanField(default=False, verbose_name='La Practica Musical Produce Una Entrada Economica Mas En El Grupo Familiar')),
                ('viv_mej', models.BooleanField(default=False, verbose_name='Ahora Vivo Mejor')),
                ('otra_razon', models.CharField(max_length=100, verbose_name='Otra Razon')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('cedula_profesor', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Cedula Del Profesor')),
                ('nombre_profesor', models.CharField(max_length=100, verbose_name='Nombre Del Profesor')),
                ('apellido_profesor', models.CharField(max_length=100, verbose_name='Apellido Del Profesor')),
                ('asignacion', models.CharField(choices=[('Programa Alma Llanera', 'Programa Alma Llanera'), ('Arpa Clasica', 'Arpa Clasica'), ('Orquesta Infantil', 'Orquesta Infantil'), ('Oboe', 'Oboe'), ('Cuatro', 'Cuatro'), ('Percusion', 'Percusion'), ('Violincello', 'Violincello'), ('Trombon', 'Trombon'), ('Coro/Lenguaje Musical', 'Coro/Lenguaje Musical'), ('Flauta/Lenguaje Musical', 'Flauta/Lenguaje Musical'), ('Corno', 'Corno'), ('Guitarra', 'Guitarra'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Viola/Lenguaje Musical', 'Viola/Lenguaje Musical'), ('Flauta', 'Flauta'), ('Clarinete', 'Clarinete'), ('Tuba', 'Tuba'), ('Trompeta/Lenguaje Musical', 'Trompeta/Lenguaje Musical'), ('Contrabajo', 'Contrabajo'), ('Pianista', 'Pianista')], default=0, max_length=40, verbose_name='Asignacion Que Ejerce')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('cedula_repres', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Cedula Del Representante')),
                ('nombre_repres', models.CharField(max_length=50, verbose_name='Nombre Del Representante')),
                ('apelli_repres', models.CharField(max_length=50, verbose_name='Apellido Del Representante')),
                ('ocupacion', models.CharField(choices=[(b'', b'---------'), (b'Comerciante', b'Comerciante'), (b'Barbero', b'Barbero'), (b'Estudiante', b'Estudiante'), (b'Empleadoa', b'Empleado(a)'), (b'Jubiladoa', b'Jubilado(a)'), (b'Tecnico', b'Tecnico'), (b'Pensionadoa', b'Pensionado(a)'), (b'Obreroa', b'Obrero(a)'), (b'Educadora', b'Educador(a)'), (b'Pastora', b'Pastor(a)'), (b'Herrero', b'Herrero'), (b'Maternal', b'Maternal'), (b'Soldador', b'Soldador'), (b'Estilita', b'Estilita'), (b'Manicurista', b'Manicurista'), (b'Amao_de_casa', b'Ama(o) de casa'), (b'Nutricionista', b'Nutricionista'), (b'Obreroa_Educacional', b'Obrero(a) Educacional'), (b'Contador', b'Contador'), (b'Cocineroa', b'Cocinero(a)'), (b'Policia', b'Policia'), (b'Administradorar', b'Administrador(ar)'), (b'Promotora_Socia', b'Promotor(a) Social'), (b'Docente', b'Docente'), (b'Custodio', b'Custodio'), (b'Pencionadoa', b'Pencionado(a)'), (b'Mecanico', b'Mecanico'), (b'Abogadoa', b'Abogado(a)'), (b'Chofer', b'Chofer'), (b'Empleadoa_Publico', b'Empleado(a) Publico'), (b'Laboratorista', b'Laboratorista'), (b'Peluqueroa', b'Peluquero(a)'), (b'Educadora', b'Educador(a)'), (b'Agricultora', b'Agricultor(a)'), (b'TSU', b'TSU'), (b'Enfermeroa', b'Enfermero(a)'), (b'Carpinteroa', b'Carpintero(a)'), (b'Ambientalista', b'Ambientalista'), (b'Militar', b'Militar'), (b'Albanil', b'Alba\xc3\xb1il'), (b'Secretariao', b'Secretaria(o)'), (b'Deportista', b'Deportista'), (b'Vigilante', b'Vigilante'), (b'Costurera', b'Costurera'), (b'Discapacidad', b'Discapacidad'), (b'Camarerao', b'Camarera(o)'), (b'Luc_social', b'Luc. social'), (b'Ejecutivoa_Bancaria', b'Ejecutivo(a) Bancaria'), (b'Otroa', b'Otros(as)')], max_length=100, verbose_name='Ocupacion Actual')),
                ('profesion', models.CharField(max_length=100, verbose_name='Profesion')),
                ('telef_cel', models.IntegerField(verbose_name='Telefono Celular')),
                ('telef_res', models.IntegerField(verbose_name='Telefono De Residencia')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_par_naci', models.BooleanField(default=False, verbose_name='Copia De La Partida De Nacimiento')),
                ('cop_ced_id_a', models.BooleanField(default=False, verbose_name='Copia De La Cedula Del Alumno')),
                ('cop_ced_id_r', models.BooleanField(default=False, verbose_name='Copia De La Cedula Del Representante')),
                ('fot_tip_car_alm', models.BooleanField(default=False, verbose_name='Foto Tipo Carnet Del Alumno')),
                ('fot_tip_car_rep', models.BooleanField(default=False, verbose_name='Foto Tipo Carnet Del Representante')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id_vivienda', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_vivien', models.CharField(choices=[('Casa', 'Casa'), ('Quinta', 'Quinta'), ('Apartamento', 'Apartamento'), ('Anexo', 'Anexo'), ('Vivienda Rural', 'Vivienda Rural'), ('Otra', 'Otra')], default=6, max_length=15, verbose_name='Tipo De Vivienda')),
                ('zona', models.CharField(max_length=100)),
                ('sevicios_basicos', models.CharField(max_length=100)),
                ('artefactos', models.CharField(choices=[('Nevera', 'Nevera'), ('Cocina', 'Cocina'), ('Lavadora', 'Lavadora'), ('Secadora', 'Secadora'), ('Computadora', 'Computadora'), ('Celular', 'Celular'), ('Telefono Fijo', 'Telefono Fijo'), ('Calentador De Agua', 'Calentador De Agua')], default=8, max_length=25)),
                ('habitacione', models.IntegerField(verbose_name='Cuantas Habitaciones Hay En La Vivienda?')),
                ('num_habitan', models.IntegerField(verbose_name='Numero De Habitantes')),
                ('num_bano', models.IntegerField(verbose_name='Numero De Ba\xf1os')),
                ('habitan_tra', models.IntegerField(verbose_name='Cuantos Habitantes Trabajan?')),
                ('habitan_apo', models.IntegerField(verbose_name='Cuantos Habitantes Aportan?')),
                ('mon_apr_men', models.IntegerField(verbose_name='Monto Monetario Mensual')),
                ('cedula_alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='percep_repre',
            name='cedula_repres',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Representante'),
        ),
    ]
