# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20171120_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='sevicios_basicos',
        ),
        migrations.AddField(
            model_name='vivienda',
            name='agua',
            field=models.BooleanField(default=1, verbose_name='Agua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='aseo_urbano',
            field=models.BooleanField(default=1, verbose_name='Aseo Urbano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='cloacas',
            field=models.BooleanField(default=1, verbose_name='Cloacas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='internet',
            field=models.BooleanField(default=1, verbose_name='Internet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='telefono_fijo',
            field=models.BooleanField(default=1, verbose_name='Telefono Fijo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cedula_alumno',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='lugar_nacimiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nacionalidad',
            field=models.CharField(choices=[('V', 'V'), ('E', 'E')], default=2, max_length=5),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='primer_apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='primer_nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='segundo_apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='segundo_nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo_alumno',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='artefactos',
            field=models.BooleanField(choices=[('Nevera', 'Nevera'), ('Cocina', 'Cocina'), ('Lavadora', 'Lavadora'), ('Secadora', 'Secadora'), ('Computadora', 'Computadora'), ('Celular', 'Celular'), ('Telefono Fijo', 'Telefono Fijo'), ('Calentador De Agua', 'Calentador De Agua')], default=8, max_length=25),
        ),
    ]
