# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-24 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20171121_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='artefactos',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='disponibles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='calentador_de_agua',
            field=models.BooleanField(default=1, verbose_name='Calentador De Agua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='celular',
            field=models.BooleanField(default=1, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='cocina',
            field=models.BooleanField(default=1, verbose_name='Cocina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='computadora',
            field=models.BooleanField(default=1, verbose_name='Computadora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='lavadora',
            field=models.BooleanField(default=1, verbose_name='Lavadora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='nevera',
            field=models.BooleanField(default=1, verbose_name='Nevera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='secadora',
            field=models.BooleanField(default=1, verbose_name='Secadora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='codigo_act',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_fina',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_inic',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombr_acti',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='apt_casa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='barri_urban',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle_avend',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='entid_feder',
            field=models.CharField(choices=[('Distrito Capital', 'Distrito Capital'), ('Miranda', 'Miranda'), ('Aragua', 'Aragua'), ('Monagas', 'Monagas'), ('Falcon', 'Falcon'), ('Carabobo', 'Carabobo'), ('Nueva Esparta', 'Nueva Esparta'), ('Anzoategui', 'Anzoategui'), ('Vargas', 'Vargas'), ('Zulia', 'Zulia'), ('Bolivar', 'Bolivar'), ('Lara', 'Lara'), ('Merida', 'Merida'), ('Tachira', 'Tachira'), ('Guarico', 'Guarico'), ('Cojedes', 'Cojedes'), ('Trujillo', 'Trujillo'), ('Barinas', 'Barinas'), ('Sucre', 'Sucre'), ('Yaracuy', 'Yaracuy'), ('Portuguesa', 'Portuguesa'), ('Delta Amacuro', 'Delta Amacuro'), ('Apure', 'Apure'), ('Amazonas', 'Amazonas')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='telef_cel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familia',
            name='telef_res',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familia',
            name='vive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombr_instr',
            field=models.CharField(choices=[('Programa Alma Llanera', 'Programa Alma Llanera'), ('Arpa Clasica', 'Arpa Clasica'), ('Orquesta Infantil', 'Orquesta Infantil'), ('Oboe', 'Oboe'), ('Cuatro', 'Cuatro'), ('Percusion', 'Percusion'), ('Violincello', 'Violincello'), ('Trombon', 'Trombon'), ('Coro/Lenguaje Musical', 'Coro/Lenguaje Musical'), ('Flauta/Lenguaje Musical', 'Flauta/Lenguaje Musical'), ('Corno', 'Corno'), ('Guitarra', 'Guitarra'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Viola/Lenguaje Musical', 'Viola/Lenguaje Musical'), ('Flauta', 'Flauta'), ('Clarinete', 'Clarinete'), ('Tuba', 'Tuba'), ('Trompeta/Lenguaje Musical', 'Trompeta/Lenguaje Musical'), ('Contrabajo', 'Contrabajo'), ('Pianista', 'Pianista')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='stock_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='stock_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='uso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido_profesor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='asignacion',
            field=models.CharField(choices=[('Programa Alma Llanera', 'Programa Alma Llanera'), ('Arpa Clasica', 'Arpa Clasica'), ('Orquesta Infantil', 'Orquesta Infantil'), ('Oboe', 'Oboe'), ('Cuatro', 'Cuatro'), ('Percusion', 'Percusion'), ('Violincello', 'Violincello'), ('Trombon', 'Trombon'), ('Coro/Lenguaje Musical', 'Coro/Lenguaje Musical'), ('Flauta/Lenguaje Musical', 'Flauta/Lenguaje Musical'), ('Corno', 'Corno'), ('Guitarra', 'Guitarra'), ('Violin', 'Violin'), ('Viola', 'Viola'), ('Viola/Lenguaje Musical', 'Viola/Lenguaje Musical'), ('Flauta', 'Flauta'), ('Clarinete', 'Clarinete'), ('Tuba', 'Tuba'), ('Trompeta/Lenguaje Musical', 'Trompeta/Lenguaje Musical'), ('Contrabajo', 'Contrabajo'), ('Pianista', 'Pianista')], default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cedula_profesor',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre_profesor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='representante',
            name='apelli_repres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cedula_repres',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='representante',
            name='nombre_repres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='representante',
            name='ocupacion',
            field=models.CharField(choices=[(b'', b'---------'), (b'Comerciante', b'Comerciante'), (b'Barbero', b'Barbero'), (b'Estudiante', b'Estudiante'), (b'Empleadoa', b'Empleado(a)'), (b'Jubiladoa', b'Jubilado(a)'), (b'Tecnico', b'Tecnico'), (b'Pensionadoa', b'Pensionado(a)'), (b'Obreroa', b'Obrero(a)'), (b'Educadora', b'Educador(a)'), (b'Pastora', b'Pastor(a)'), (b'Herrero', b'Herrero'), (b'Maternal', b'Maternal'), (b'Soldador', b'Soldador'), (b'Estilita', b'Estilita'), (b'Manicurista', b'Manicurista'), (b'Amao_de_casa', b'Ama(o) de casa'), (b'Nutricionista', b'Nutricionista'), (b'Obreroa_Educacional', b'Obrero(a) Educacional'), (b'Contador', b'Contador'), (b'Cocineroa', b'Cocinero(a)'), (b'Policia', b'Policia'), (b'Administradorar', b'Administrador(ar)'), (b'Promotora_Socia', b'Promotor(a) Social'), (b'Docente', b'Docente'), (b'Custodio', b'Custodio'), (b'Pencionadoa', b'Pencionado(a)'), (b'Mecanico', b'Mecanico'), (b'Abogadoa', b'Abogado(a)'), (b'Chofer', b'Chofer'), (b'Empleadoa_Publico', b'Empleado(a) Publico'), (b'Laboratorista', b'Laboratorista'), (b'Peluqueroa', b'Peluquero(a)'), (b'Educadora', b'Educador(a)'), (b'Agricultora', b'Agricultor(a)'), (b'TSU', b'TSU'), (b'Enfermeroa', b'Enfermero(a)'), (b'Carpinteroa', b'Carpintero(a)'), (b'Ambientalista', b'Ambientalista'), (b'Militar', b'Militar'), (b'Albanil', b'Alba\xc3\xb1il'), (b'Secretariao', b'Secretaria(o)'), (b'Deportista', b'Deportista'), (b'Vigilante', b'Vigilante'), (b'Costurera', b'Costurera'), (b'Discapacidad', b'Discapacidad'), (b'Camarerao', b'Camarera(o)'), (b'Luc_social', b'Luc. social'), (b'Ejecutivoa_Bancaria', b'Ejecutivo(a) Bancaria'), (b'Otroa', b'Otros(as)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='representante',
            name='profesion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='representante',
            name='telef_cel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='representante',
            name='telef_res',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='habitacione',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='habitan_apo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='habitan_tra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='mon_apr_men',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='num_bano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='num_habitan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='tipo_vivien',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Quinta', 'Quinta'), ('Apartamento', 'Apartamento'), ('Anexo', 'Anexo'), ('Vivienda Rural', 'Vivienda Rural'), ('Otra', 'Otra')], default=6, max_length=15),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='zona',
            field=models.CharField(max_length=100, verbose_name='Zona'),
        ),
    ]
